service: trailstopper
app: trailstopper-app
org: leoyockey

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-2

iamRoleStatements:
   - Effect: "Allow"
     Action:
       - "s3:ListBucket"
     Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "mbc-stocks" } ] ]  }
   - Effect: "Allow"
     Action:
       - "s3:PutObject"
     Resource:
       Fn::Join:
         - ""
         - - "arn:aws:s3:::"
           - "Ref" : "mbc-stocks"
           - "/*"
environment:
  SLS_DEBUG: "*"

functions:
  trailStopper:
    handler: index.handler
    events:
      - schedule: cron(50 19 ? * MON-FRI *)
    environment:
      - ACCESS_TOKEN_KEY: $(ACCESS_TOKEN_KEY)
      - ACCESS_TOKEN_SECRET: $(ACCESS_TOKEN_SECRET)
      - CONSUMER_KEY: $(CONSUMER_KEY)
      - CONSUMER_SECRET: $(CONSUMER_SECRET)
      - S3_BUCKET: $(S3_BUCKET)
      - STOCKS: $(STOCKS)
      - TOPIC_ARN: $(TOPIC_ARN)

