on:
  push:
    branches:
      - master
name: Deploy master branch
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: npm install
      uses: actions/npm@master
      with:
        args: install
    - name: serverless deploy
      uses: serverless/github-action@master
      with:
        args: deploy
      env:
        ACCESS_TOKEN_KEY: ${{secrets.ACCESS_TOKEN_KEY}}
        ACCESS_TOKEN_SECRET: ${{secrets.ACCESS_TOKEN_SECRET}}
        CONSUMER_KEY: ${{secrets.CONSUMER_KEY}}
        CONSUMER_SECRET: ${{secrets.CONSUMER_SECRET}}
        S3_BUCKET: ${{secrets.S3_BUCKET}}
        STOCKS: ${{secrets.STOCKS}}
        TOPIC_ARN: ${{secrets.TOPIC_ARN}}